name: Mi Primer Pipeline CI/CD

# Esto dice: "Ejecútame cada vez que alguien guarde cambios"
on: [push]

jobs:
  # ETAPA 1: CONSTRUIR
  build:
    runs-on: windows-latest
    steps:
      - name: Obtener el código
        uses: actions/checkout@v3
      - name: Instalar dependencias
        run: pip install python-dotenv

  # ETAPA 2: PROBAR (Testing)
  test:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Obtener el codigo
        uses: actions/checkout@v3
      
      - name: Instalar dependencias
        run: pip install python-dotenv
      
      - name: Crear archivo de configuración de test
        run: |
          echo "ENVIRONMENT=testing" > config/testing.env
          echo "DB_HOST=localhost" >> config/testing.env
          echo "DB_NAME=mi_proyecto_test" >> config/testing.env
      
      - name: Ejecutar Tests de QA
        run: python -m unittest tests/test_app.py
        env:
          ENVIRONMENT: testing
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: mi_proyecto_test

  # ETAPA 3: DESPLEGAR
  deploy:
    needs: test   # "Espera a que terminen los Tests"
    runs-on: windows-latest
    steps:
      - name: Simular despliegue a producción
        run: echo "✅ ¡Tests pasaron! Enviando código al servidor..."
